### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "1999-02-22",
  "registeredDate": "2023-12-22"
}
###